### ISSUE TITLE
Device Unavailable

### ISSUE THREAD

**Issue by mickeyger** [DnG-Crafts/Xmas-Control#1]
I have added my FPP player on the app recognises the IP and says the device in Online. However when selecting the device it gives a message "Device Unavailable" . Any ideas what Im doing wrong? Thanks for the app. Brilliant idea.
![Xmas Control error](https://github.com/user-attachments/assets/822a5bf1-408d-4e54-ac04-d6031149cb77)

**Comment by DnG-Crafts** [comment]
what version of fpp are you using and what type of device is fpp running on like a raspberry pi, beagle etc?

**Comment by mickeyger** [comment]
![FPP version](https://github.com/user-attachments/assets/ddae9105-a72a-4c74-933a-106d19c3938d)

Raspberry Pi 5 
FPP v2024-02

**Comment by DnG-Crafts** [comment]
i thought it might have been an old fpp but i was testing out 6 and it still worked but i think i know what the issue is.

i took a guess that you had the password enabled for the ui which blocks unauthenticated access to the rest api so i added the code to deal with that.

to add the password to the existing device just long press the device in the list until the popup appears, click edit then tick "ui has authentication" and you will be able to set the user and pass and hit save.

it should begin to work after that.

if you are installing the app from the google play store it will take a while for google to review and post it.

 
![editdialog](https://github.com/user-attachments/assets/aa538dfd-bb5b-405e-9d85-911ba60ccc10)

**Comment by mickeyger** [comment]
Thanks , will give this a try and let you know. Once again appreciate you
sharing 🙏

**Comment by mickeyger** [comment]
Thanks that worked... gonna give it a try tonight

**Comment by mickeyger** [comment]
works perfectly.... can connect to FPP.... will test on lights later. Thanks a million

**Comment by DnG-Crafts** [comment]
i had to do another small update as i noticed i was not passing the auth to the playlist and sequence activity classes causing them to fail to work correctly.
